FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app
EXPOSE 7050
EXPOSE 7060

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
WORKDIR /src
COPY ["Backend/HdiCase.RestApi/HdiCase.RestApi.csproj", "./"]
COPY ["Backend/HdiCase.Interfaces/HdiCase.Interfaces.csproj", "./"]
COPY ["Backend/HdiCase.Models/HdiCase.Models.csproj", "./"]
COPY ["Backend/HdiCase.Services/HdiCase.Services.csproj", "./"]
RUN dotnet restore -a $TARGETARCH "HdiCase.RestApi.csproj"
COPY ./Backend .

RUN dotnet build -a $TARGETARCH "HdiCase.RestApi/HdiCase.RestApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -a $TARGETARCH "HdiCase.RestApi/HdiCase.RestApi.csproj" --no-restore -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HdiCase.RestApi.dll"] 



